### ISSUE TITLE
Instantiating Query... Please Help!

### ISSUE THREAD

**Issue by manhiem** [BoltEngine/Bolt-Sample#5]
I am building an Augmented reality First Person Shooter. My idea on building this game is that a gameobject spawns on the location of the Host and the Client and follows them respectively. This gameobject can be used as a collider to detect when raycasting. But the problem i am facing is that both the gameobjects are spawning at the same position and following my camera in my view and opponents camera in his view. The reason that i am thinking is that there are two cameras in the scene and hence both the gameobjects are reacting to both the cameras in their own way. So we cannot differentiate the client and host in their respective cameras.

if(BoltNetwork.IsClient)
{
GameObject Player1 = BoltNetwork.Instantiate(BoltPrefabs.Player1, Vector3.zero, this.gameobject.transform.rotation);
}
if(BoltNetwork.IsServer)
{
GameObject Player2 = BoltNetwork.Instantiate(BoltPrefabs.Player2, Vector3.zero, this.gameobject.transform.rotation);
}

This is the code i am using.

Thanks in Advance!!!!
: )

**Comment by ramonmelo** [comment]
Hello @manhiem ,

Please, send us an email to developer@photonengine.com, so we can take a better look.
We also have an Issue Tracker that you can use (https://github.com/BoltEngine/Bolt-Tracker/issues).
This repository is only for the Bolt Samples.

Also, just as a quick thought, generally on cases like this, each entity has its own camera, but it's disabled by default.
When a specific player creates it (https://doc-api.photonengine.com/en/bolt/current/class_bolt_1_1_entity_behaviour.html#a21d8a26e1e8197164ea49ee5a7a5a640 plus `entity.IsOwner`) or gains control (https://doc-api.photonengine.com/en/bolt/current/class_bolt_1_1_entity_behaviour.html#a09ddf209aa2ac133ecbb209cb8d9ddb7) over the entity, the local camera of that entity is enabled, so you don't have multiple cameras.
